Atualizando o método listarIniciacaoCiencifica
uspdev/replicado pull request #437
Opened 2021-05-26 01:00 UTC by st-ricardof

Este método agora não listará apenas as iniciações científicas ativas, ele permite listar através de filtros por data.
Obs: Método usado no portal de dados da fflch

2021-05-26 14:24 UTC, masakik requested changes
Ola, tem várias coisinhas aqui que tornam exclusivo para FFLCH
- no sql tem usado ...fflch.dbo.SETOR....
- ic.codundprj = __unidades__ teria de ser ic.codundprj IN (__unidades__)
-  usando ANO_INI para  mais de uma função não parece uma boa idéia. Não seria melhor usar outra variável $somenteAtivos = true||false ?
- vários métodos estão com query da fflch somente *************

2021-05-26 14:25 UTC, masakik commented
No caso de setor, não seria o caso de poder passar mais de um também na forma de lista de setores?

2021-05-26 19:38 UTC, st-ricardof commented
Ajustes feitos, para os apontamentos mais gerais, como o  codundprj  e fflch.dbo arrumei todas as querys que tinham isso, não só as das Iniciações Científicas.

2021-05-27 16:18 UTC, thiagogomesverissimo commented
Acho que tudo foi resolvido =)

2021-05-27 16:19 UTC, merged