Adicionando opção de retornar o email usp nos métodos para listar docentes, servidores e designados
uspdev/replicado pull request #461
Opened 2021-07-12 19:09 UTC by st-ricardof

2021-07-12 19:22 UTC, st-ricardof commented
Tem dois commits com a descrição  "Fix issue #457" , porém o primeiro é referente à issue #458. Assim, as duas issues #457 e #458 foram resolvidas.

2021-07-12 22:40 UTC, masakik commented on src/Pessoa.php
> +            'codundclg' => $unidades,
$unidades é uma lista separado por virgulas. Não pode ser passado por param

2021-07-12 22:43 UTC, masakik requested changes
Não é melhor separar as issues?
Fazendo review já vi que codund clg foi colocado nos params e não pode se pegar do env.
No método designados, já que está alterando os parametros, já não é o caso de renomear para listarDesignados e remover o codundclg dos parametros para atender ao padrão?

2021-07-16 18:13 UTC, st-ricardof commented
Beleza, estou fechando a PR para poder separar as issues.

2021-07-16 18:13 UTC, closed without merging