Alterações no método designados na classe Pessoa
uspdev/replicado pull request #464
Opened 2021-07-19 15:24 UTC by st-ricardof

Se $tipvinext for igual a um array vazio a query vai continuar como era antes, a alteração feita é para poder selecionar os designados de acordo com um vínculo específico. Assim é possível pegar apenas os servidores designados, ou os docentes designados.

2021-07-21 13:07 UTC, masakik requested changes
o método designados não está sendo usado por ninguém? pois se vc alterou o nome quem estiver usando não vai mais conseguir;
para mim não funcionou, como tinha comentado no outro PR codundclg ( enão codundclgi) não pode ser atribuído por param pois é uma lista separada por vírgula;
O tipvinext pode ser servidor ou docente apenas? Nesse caso não poderia passar direto a string (Docente ou Servidor) sem ser array? E par não confundir poderia chamar categ ao inves de tipvinext;

2021-07-22 19:51 UTC, st-ricardof commented
Feito, eu alterei o tipvinext para categoria, no entanto, em vez de string coloquei como inteiro, para evitar strings incorretas, já que existe apenas 2 opções mesmo.

2021-08-12 22:52 UTC, thiagogomesverissimo commented
Parece ok agora né @masakik ?

2021-08-13 14:37 UTC, masakik commented
O ricardo não resolveu o ultimo comentário sobre passar codundclg por parâmetro.

2021-08-13 15:20 UTC, st-ricardof commented
O listarDesignados só recebe um parametro, que é a categoria.

Em relação ao antigo método eu deixei este comentário:  "$codundclgi. O valor deste parâmetro não está mais sendo utilizado, o código da unidade agora é obtido através da configuração no .env"
Como pode-se notar na linha 905
 /**
     * (deprecated) Método para retornar servidores designados ativos na unidade
     *
     * @param Integer $codundclgi. O valor deste parâmetro não está mais sendo utilizado, o código da unidade agora é obtido através da configuração no .env
     * @return Array
     * @deprecated em favor de listarDesignados, em 22/07/2021 - @st-ricardof.
     */
    public static function designados($codundclgi)
    {
        return self::listarDesignados();
    }

2021-08-13 15:29 UTC, masakik requested changes

2021-08-13 15:36 UTC, masakik commented
Desculpe, eu tinha começado um review mas não tinha submetido. Mas aparecei para mim na tela.
Na linha 225,
                        AND L.codundclg IN (convert(int,:codundclg))
 se $codundclg pode ser uma lista não tem como converter para int nem passar no array de $param. 
Veja a linha 554 como deve ser:
                        AND LOCALIZAPESSOA.codundclg IN ({$unidades})

2021-08-13 15:52 UTC, st-ricardof commented
Tem razão, obg Masaki. Serei mais cuidadoso nos PRs futuros.

2021-08-13 18:19 UTC, merged

2021-08-13 18:20 UTC, masakik commented
:1st_place_medal: